### PR TITLE
QRCode: New App - Initial Commit

### PR DESCRIPTION
**Pull request by import-au**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [x] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [x] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [x] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- Initial Release. This app implements opencv's capability to decode a QR Code.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by pdesai-crest** [comment]
Hi @import-au 

There are few suggestions:

1. In Publisher and License, you have written “Community”. There is no specification about community. So can you please specify that part and change Publisher and License?? Or else we can write Splunk Community in Publisher and License.

2. You have mentioned min_phantom_version": "5.3.2.88192" but as of now Minimum phantom version is 6.0.2, so please change min_phantom_version and test it. If you have any concerns regarding this, then tell us.

Consider above suggestion. If you have any query then reach out to us.

**Comment by import-au** [comment]
1. Splunk Community is fine.
2. I do not have a 6.0.2 instance to test this with at this time. I'm fine if you update it as long as you can test that it works as well.

**Comment by pdesai-crest** [comment]
> 1. Splunk Community is fine.
> 2. I do not have a 6.0.2 instance to test this with at this time. I'm fine if you update it as long as you can test that it works as well.

Hello @import-au 

With respect to above points,
1. We are adding Splunk Community in License and Publisher
2. We are keeping Minimum Phantom Version as it is. That means minimum phantom version is 5.3.2.88192 . We are not changing it.

**Review by tonyc-phantom — DISMISSED** [review]

**Comment by import-au** [comment]
What is needed to move this forward?

**Comment by pdesai-crest** [comment]
> What is needed to move this forward?

We are blocked on

> What is needed to move this forward?

There are 24 issues in FOSSA scan due to “opencv-python-headless” module. We are blocked on this. Once there is conclusion, will let you know.

If you have any query, then let us know.

**Comment by pdesai-crest** [comment]
> What is needed to move this forward?

There are 24 issues in FOSSA scan due to “opencv-python-headless” module. We are blocked on this. Once there is conclusion, will let you know.

If you have any query, then let us know.

**Comment by pdesai-crest** [comment]
Hello @import-au 

There are few suggestions/concerns.

It would be ideal if can remove some flags for certain “included” files as described below.
If either of the items below are NOT USED or NOT ESSENTIAL for your ability to make use of opencv, please remove if possible to do so:

1.  opencv/3rdparty/ittnotify/include/llvm_jit_event_listener.hpp 

WHY ASKING TO REMOVE IF POSSIBLE: There is a banner in the Github repo that indicates this component “does not belong to any branch of the opencv-python repository” -- if true, why showing up in the FOSSA scan for Phantom QR App? And **`if non-essential, can it be removed??`**

2.  opencv/doc/pattern_tools/svgfig.py

WHY ASKING TO REMOVE IF POSSIBLE: This is a component included in opencv-python-headless that’s itself GPL licensed. **`If not needed or if not used, request that remove this file- (https://github.com/opencv/opencv/blob/4.x/doc/pattern_tools/svgfig.py)`**

**Comment by pdesai-crest** [comment]
> Hello @import-au
> 
> There are few suggestions/concerns.
> 
> It would be ideal if can remove some flags for certain “included” files as described below. If either of the items below are NOT USED or NOT ESSENTIAL for your ability to make use of opencv, please remove if possible to do so:
> 
> 1. opencv/3rdparty/ittnotify/include/llvm_jit_event_listener.hpp
> 
> WHY ASKING TO REMOVE IF POSSIBLE: There is a banner in the Github repo that indicates this component “does not belong to any branch of the opencv-python repository” -- if true, why showing up in the FOSSA scan for Phantom QR App? And **`if non-essential, can it be removed??`**
> 
> 2. opencv/doc/pattern_tools/svgfig.py
> 
> WHY ASKING TO REMOVE IF POSSIBLE: This is a component included in opencv-python-headless that’s itself GPL licensed. **`If not needed or if not used, request that remove this file- (https://github.com/opencv/opencv/blob/4.x/doc/pattern_tools/svgfig.py)`**

Hello @import-au 
Can you please look into this?

**Comment by import-au** [comment]
> > Hello @import-au
> > There are few suggestions/concerns.
> > It would be ideal if can remove some flags for certain “included” files as described below. If either of the items below are NOT USED or NOT ESSENTIAL for your ability to make use of opencv, please remove if possible to do so:
> > 
> > 1. opencv/3rdparty/ittnotify/include/llvm_jit_event_listener.hpp
> > 
> > WHY ASKING TO REMOVE IF POSSIBLE: There is a banner in the Github repo that indicates this component “does not belong to any branch of the opencv-python repository” -- if true, why showing up in the FOSSA scan for Phantom QR App? And **`if non-essential, can it be removed??`**
> > 
> > 2. opencv/doc/pattern_tools/svgfig.py
> > 
> > WHY ASKING TO REMOVE IF POSSIBLE: This is a component included in opencv-python-headless that’s itself GPL licensed. **`If not needed or if not used, request that remove this file- (https://github.com/opencv/opencv/blob/4.x/doc/pattern_tools/svgfig.py)`**
> 
> Hello @import-au Can you please look into this?

I do not believe either of these are necessary for the functionality I am introducing. I don't own those repositories so I'm unsure what steps you'd like me to take.

**Comment by import-au** [comment]
@pdesai-crest please advise

**Comment by pdesai-crest** [comment]
Considering that suggestions provided by legal team are not feasible over here because they said for removal of files from library and we are not owner of that library as well as we use wheel files of lib. So that suggestions are not feasible and as they have given clearance - we are proceeding for next steps

**Comment by pdesai-crest** [comment]
> @pdesai-crest please advise

We are proceeding further to release the app.

**Comment by import-au** [comment]
@pdesai-crest what is needed here? 3 weeks to release seems excessive?

**Review by alexa-phantom — APPROVED** [review]

**Review by tonyc-phantom — APPROVED** [review]

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
